import { Router } from 'express';
import { resolveTicket } from '../agents/actionAgent.js';

const VALID_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED'];
// Ticket IDs are always generated by the Action Agent as CP<number> (see
// ticketsRepo.nextTicketId). Rejecting anything else here means malformed
// or hostile :id values never reach a SQL string.
const TICKET_ID_PATTERN = /^CP\d+$/;

export function ticketsRouter({ repo }) {
  const router = Router();

  router.get('/', async (_req, res) => {
    try {
      const tickets = await repo.listTickets();
      res.json(tickets);
    } catch (err) {
      console.error('GET /api/tickets failed:', err);
      res.status(500).json({ error: 'Failed to list tickets' });
    }
  });

  router.get('/:id', async (req, res) => {
    if (!TICKET_ID_PATTERN.test(req.params.id)) {
      return res.status(404).json({ error: 'Ticket not found' });
    }
    try {
      const ticket = await repo.getTicket(req.params.id);
      if (!ticket) return res.status(404).json({ error: 'Ticket not found' });
      res.json(ticket);
    } catch (err) {
      console.error('GET /api/tickets/:id failed:', err);
      res.status(500).json({ error: 'Failed to get ticket' });
    }
  });

  router.put('/:id', async (req, res) => {
    if (!TICKET_ID_PATTERN.test(req.params.id)) {
      return res.status(404).json({ error: 'Ticket not found' });
    }
    const { status } = req.body ?? {};
    if (!VALID_STATUSES.includes(status)) {
      return res.status(400).json({ error: `status must be one of ${VALID_STATUSES.join(', ')}` });
    }

    try {
      const updated = await resolveTicket({ repo, ticketId: req.params.id, status });
      if (!updated) return res.status(404).json({ error: 'Ticket not found' });
      res.json(updated);
    } catch (err) {
      console.error('PUT /api/tickets/:id failed:', err);
      res.status(500).json({ error: 'Failed to update ticket' });
    }
  });

  return router;
}
